### ISSUE TITLE
[FEAT]: Create a table for the issue section with data about the issue .

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#10]
Create a table for the issue section with data about the issue.

The table should have the following information: 
- Name of repo
- Issue Link 
- Technology/Language used
- Status ( Open/Closed)

**Comment by poorvijn** [comment]
Hello, this is for the issue section on the readme file right?

**Comment by ArslanYM** [comment]
> Hello, this is for the issue section on the readme file right?

Yes poorvi.

**Comment by ArslanYM** [comment]
Assigned to you @poorvijn

**Comment by Sivasish48** [comment]
Can I be assigned ??

**Comment by ArslanYM** [comment]
> Can I be assigned ??

Poorvi is already assigned and working on it. Try out other issues.

**Comment by poorvijn** [comment]
Hello, I tried creating the table and here's how it looks: 

![markdowntable](https://github.com/ArslanYM/StarterHive/assets/87180220/e6418b2c-b877-4074-b86e-3dc2b2b5a6fb)

Would you like me to make some changes?

**Comment by ArslanYM** [comment]
@poorvijn Great work!! That would be enough for now!

**Comment by poorvijn** [comment]
Thank you! I've created a pull request for the same, had fun doing this!

**Comment by gabrysia694** [comment]
Hello, is this table supposed to be filled out with repositories good for beginners? If so, can I add my two repositories that fit the description?

**Comment by gabrysia694** [comment]
> @gabrysia694 No. For now I think you can add some data for sure. But The project will be soon running on an API. I dont see any point of adding that data now.

oh okay, I understand now. So maybe I'll add one beginner-friendly repository just to set an example of what it should look like.

**Comment by ArslanYM** [comment]
Please go for it!! @gabrysia694

**Comment by ArslanYM** [comment]
Completed!
