### ISSUE TITLE
🔴 BUG: Button with less padding

### ISSUE THREAD

**Issue by masif2002** [ArslanYM/StarterHive#101]
## Description
Feel like the padding on this button is a bit too less
![image](https://github.com/ArslanYM/StarterHive/assets/94846379/83ee3df4-c3d0-48a1-8372-a77bb10c0cd3)

### Steps to Reproduce
1. Go to the [website](https://starter-hive.vercel.app/)
2. Take a look at the GitHub button on the NavBar

## Proposed Change
![image](https://github.com/ArslanYM/StarterHive/assets/94846379/8e60ef43-5a6e-4670-85c4-73ea4ae9f5ab)

Note: I have also removed the Arrow icon in the proposal

**Comment by ArslanYM** [comment]
@masif2002 Pretty cool , wanna get assigned?

**Comment by masif2002** [comment]
I thought you assigned it to me :P @ArslanYM

**Comment by ArslanYM** [comment]
@masif2002 haha, @rahilansari261 he made a PR so had to merge. Find some other issue my guy
