### ISSUE TITLE
⭐FEAT: Add images to the hero divs

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#102]
# TODO: 
- Add images to divs in the main hero section.
- add more divs to fill the right portion of the hero section. Will provide more images later.
here: 
![Screenshot 2023-05-27 114139](https://github.com/ArslanYM/StarterHive/assets/104521101/071f93e1-fa32-42a6-9b1a-5632dc323184)

# images: 
![Penguinxz1_a_man_wearing_hoodie_not_showing_his_face_coding_in__09a58591-376a-468f-8541-7dc016f59dbf](https://github.com/ArslanYM/StarterHive/assets/104521101/fcf0d93f-8cc4-41e3-afb5-cbfad6f25486)
![Penguinxz1_a_man_wearing_hoodie_not_showing_his_face_coding_in__ae92f84a-ed5b-4410-96a7-eb8bc366e483](https://github.com/ArslanYM/StarterHive/assets/104521101/7d32570f-c1f1-4620-84a0-f763e1dde741)
![Penguinxz1_many_coding_community_peoples_in_a_futuristic_coding_9dd7c244-3ba7-4462-bc2c-778aa751ccb0](https://github.com/ArslanYM/StarterHive/assets/104521101/02f6dece-11f7-405a-be9f-cc4ec060bcfa)
![Penguinxz1_many_coding_community_peoples_standing_facing_camera_18d12f28-5e87-4972-b957-f196e32b247f](https://github.com/ArslanYM/StarterHive/assets/104521101/b0543c0d-9531-4c9d-94ee-a4688384fb53)

**Comment by swarajsahil** [comment]
I will do it  can you explain more about it how it look or  show me example

**Comment by ArslanYM** [comment]
@swarajsahil 
Something like this : 
![this](https://github.com/ArslanYM/StarterHive/assets/104521101/8aa52b05-d38f-414d-bb55-9d9f0107f7d0)

**Comment by swarajsahil** [comment]
ok i will do

**Comment by ArslanYM** [comment]
Dont forget to add more divs , you can keep some placeholder images in those rightnow. But we will add images later in the other d divs
