### ISSUE TITLE
🔴 BUG: navbar and hero section both are not aligned properly

### ISSUE THREAD

**Issue by rahilansari261** [ArslanYM/StarterHive#108]
**Describe the bug**
navbar and hero section both are not aligned properly Hero section has too much space to its left side

**To Reproduce**
1. Go to home page

**Expected behavior**
both hero section and navbar should align together properly

**Comment by rahilansari261** [comment]
@ArslanYM what do you think ?
i think Hero section should align accordingly navbar

**Comment by ArslanYM** [comment]
Yes I agree. That is why I have  asked to make changes to the navbar , make the navbar more aligned to he center

**Comment by rahilansari261** [comment]
Ok noted
