### ISSUE TITLE
⭐FEAT: Add navigation to the website

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#111]
# TODO:

- The user should be able to navigate to different pages using the navbar and find issue button.

**Comment by anxbt** [comment]
I opened header.jsx file in order to make changes to the navbar and ran ` npm run start`.it showed some error so i ran `echo {} >` to create "package.json" file.Still i cant run the react file. can you please guide  me

**Comment by ArslanYM** [comment]
@ArslanYM  You need to install node module first. Hit `npm install` first

**Comment by ArslanYM** [comment]
Fixed in #116
