### ISSUE TITLE
🔴 BUG: Fix hero Image 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#119]
# TODO: 
- Fix the height of these to be same.
- add floating animation to these divs

![img](https://github.com/ArslanYM/StarterHive/assets/104521101/6341c4c5-bc6a-4a24-b93d-e300e4d9fa52)

**Comment by ArslanYM** [comment]
## when images are added to these containers it looks like this, 
![fffffixx](https://github.com/ArslanYM/StarterHive/assets/104521101/54fb04a6-2710-4d3e-823f-7c29b14f9e68)

## The goal should be to increase the height and widht responsively of these divs and add floating animation as before.

**Comment by rahilansari261** [comment]
@ArslanYM i had added the floating animation to those div but after merging #116 this it gone .

**Comment by ArslanYM** [comment]
@rahilansari261 Yes youre right. There must have been conflicts that got merged. I will see to that. Can you take up this issue?

**Comment by rahilansari261** [comment]
Süre
