### ISSUE TITLE
 ⭐FEAT: Add svg in footer

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#121]
# TODO : 
- Add Starter Hive Svg In footer.
- (Link to svg)[https://github.com/ArslanYM/StarterHive/blob/main/web/public/hive.svg]
- Add it here : 
![svvg](https://github.com/ArslanYM/StarterHive/assets/104521101/29acb85d-0444-4c2f-982a-5d8924bd27e4)

**Comment by lokeshkadem** [comment]
sir,we can use the use tag in svg tag to add starterhive svg file in the footer
means

 <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" className="w-10 h-10 text-white p-2 bg-purple-500 rounded-full" viewBox="0 0 24 24">
                        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
                        <use xlink:href="../../../public/hive.svg"></use>
                    </svg>

**Comment by lokeshkadem** [comment]
<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" className="w-10 h-10 text-white p-2 bg-purple-500 rounded-full" viewBox="0 0 24 24">
                        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
                        <use xlink:href="../../../public/hive.svg"></use>
                    </svg>

**Comment by lokeshkadem** [comment]
<svg 
                        <use xlink:href="../../../public/hive.svg"></use>
                    </svg>

**Comment by lokeshkadem** [comment]
<use xlink:href=file path"></use>

**Comment by lokeshkadem** [comment]
<svg 
   <use xlink:href="../../../public/hive.svg"></use>
  </svg>

**Comment by ArslanYM** [comment]
You can try it out on your local host

**Comment by sambhavgupta0705** [comment]
hey I would like to work on this one

**Comment by ArslanYM** [comment]
> hey I would like to work on this one
> 
> 

Sure, assigned to you
