### ISSUE TITLE
⭐FEAT: Improve the issue card design

### ISSUE THREAD

**Issue by nadeem099** [ArslanYM/StarterHive#122]
## TODO:
Need improvements in the design of the issue cards as it is the main feature of the website.
- It has to be appealing and should have good ux.
- As much information as possible about the issue should be displayed in the card itself without opening the issue link, at the same time it should not be flooded with lot of info as it will affect the ux.

**Comment by kaleemullah786** [comment]
hey can i work on this.
also what more info needs to be displayed?

**Comment by kaleemullah786** [comment]
i think adding more stuff will mess things up 
one thing we can do is to add show details action. 
what do you say?

**Comment by ArslanYM** [comment]
@kaleemullah786 Yes adding more details would mess things up for sure. 
The issue card should have 
- project logo
- project name
- Organisation/company
- Issue titile
- Current status
- Tags(languages , tech stack)
- More details button to naviagate to project
-

**Comment by ArslanYM** [comment]
@kaleemullah786 Should I assign this to you/

**Comment by kaleemullah786** [comment]
Alright. 
Sure! I can work on it

**Comment by ArslanYM** [comment]
@kaleemullah786 Any progress?

**Comment by kaleemullah786** [comment]
Sorry i got busy yesterday, will try to finish today otherwise tomorrow for sure.

**Comment by ArslanYM** [comment]
@kaleemullah786 No progres

**Comment by kaleemullah786** [comment]
I've already worked on it.
See here:
https://github.com/ArslanYM/StarterHive/pull/168#issuecomment-1568662726

**Comment by ArslanYM** [comment]
Fixed.
