### ISSUE TITLE
⭐FEAT: Style the contributors section

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#124]
# TODO: 
- Style the contributors section 
 -  Make the font size bigger and better
 - Add thanking message to contributors
 
![condsf](https://github.com/ArslanYM/StarterHive/assets/104521101/dad7a2fc-2252-4d38-b930-9d7e0f5ad5f3)

**Comment by kaleemullah786** [comment]
hey i can work on it. what thanking message do you want to add?

**Comment by ArslanYM** [comment]
@kaleemullah786 A short thanking message to our talented contributors

**Comment by kaleemullah786** [comment]
alright

**Comment by ArslanYM** [comment]
fixed in #127
