### ISSUE TITLE
⭐FEAT: Create a complete Guide page 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#125]
# TODO: 
- Create a complete guide to run this project on local host
-  add images 
- keep the theme as other pages
- style the page well , keep it one pager

![guide](https://github.com/ArslanYM/StarterHive/assets/104521101/2a592d9b-5af9-4cc4-8a37-4b5dde17349a)

**Comment by Soufianeelc** [comment]
I would like to work on this section.

**Comment by ArslanYM** [comment]
I hope you understand the goal, Feel free to ask question related to this issue here or in discord.
 Assigned to you!

**Comment by Soufianeelc** [comment]
Hi @ArslanYM , a git conflict is appeared when I submited my PR. Can you help please?

**Comment by ArslanYM** [comment]
@Soufianeelc It looks like you havent updated you fork but pulling the changes for the main repository. Read [this](https://stackoverflow.com/questions/8948803/what-does-git-remote-add-upstream-help-achieve) to understand how it works.

**Comment by ArslanYM** [comment]
i guess a trick would be , save the changes you made somewhere else temporarily.  update your fork , Clone the main branch again, make a new branch , paste your changes in the file you want and create a pr

**Comment by ArslanYM** [comment]
@Soufianeelc Any progress?

**Comment by Soufianeelc** [comment]
Done ☑️

**Comment by ArslanYM** [comment]
Great Work @Soufianeelc c. Thankyou for your contribution. I would definitely love it if you can iterate more on this Guide and make it better.

**Comment by ArslanYM** [comment]
Added in #175 . Needs more iteration

**Comment by ArslanYM** [comment]
Fixed.
