### ISSUE TITLE
🔴 BUG:  Add some padding to the hero section 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#134]
# TODO:
- Add some padding to the hero section 
- the hero content should be in the center axis 
- the footer should only be visible when scrolled down
![Screenshot 2023-05-28 201128](https://github.com/ArslanYM/StarterHive/assets/104521101/72659b98-af7d-4dde-bcd4-1463f0a1671c)

**Comment by MuhammadRabi** [comment]
I can handle this bug

**Comment by ArslanYM** [comment]
@MuhammadRabi Make sure to only make necessary changes and keep the commit sufficient to 1;

**Comment by MuhammadRabi** [comment]
> @MuhammadRabi Make sure to only make necessary changes and keep the commit sufficient to 1;

sure it will take just one line in code and changing another

**Comment by medinipatil** [comment]
I want to try fix this bug.

**Comment by medinipatil** [comment]
Can you pls assign it to me

**Comment by ArslanYM** [comment]
@medinipatil It has been fixed
