### ISSUE TITLE
⭐FEAT: Add new images to HeroImg containers

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#135]
# TODO : 
- Add  new images to other containers
Here : 
![hee](https://github.com/ArslanYM/StarterHive/assets/104521101/6e1ae939-8fcf-4cf5-8d89-4633ef8d2e4d)

## Images : 
![1](https://github.com/ArslanYM/StarterHive/assets/104521101/4ef028d9-2a9e-4cba-a021-2b8e2393e21c)
![2](https://github.com/ArslanYM/StarterHive/assets/104521101/725e0f22-9d33-4908-a37b-63b0a7ae2f89)
![3](https://github.com/ArslanYM/StarterHive/assets/104521101/8a196297-e534-408a-83d6-e8813fe355c4)

**Comment by Faopaw** [comment]
I have made changes and created a pull request: https://github.com/ArslanYM/StarterHive/pull/144

**Comment by ArslanYM** [comment]
> I have made changes and created a pull request: https://github.com/ArslanYM/StarterHive/pull/144

Did you get assigned to this issue?

**Comment by Faopaw** [comment]
No, sorry about that. I completely forgot about that. Could you assign me to this issue?

Thanks.

**Comment by Ferno2k** [comment]
I would like to kindly request if it would be possible to assign this issue to me.I am eager to work on it. If there are any specific requirements or instructions related to the issue, please let me know, and I will ensure to address them promptly.

Thank you for your consideration. I'm looking forward to the opportunity to contribute to the project.

**Comment by ArslanYM** [comment]
@Ferno2k Assigned to you.

**Comment by ArslanYM** [comment]
Fixed
