### ISSUE TITLE
🔴 BUG: an extra space needs to be added before the yellow hero text

### ISSUE THREAD

**Issue by MuhammadRabi** [ArslanYM/StarterHive#138]
**Describe the bug**
There is no space between the yellow word "Open Source" and the text before it

**To Reproduce**
1. Go to home page
2. Look at the hero text

**Expected behavior**
extra space to be added before the yellow text

**Screenshots**
![](https://i.ibb.co/FHQhdzm/bug0.png)

**Comment by ArslanYM** [comment]
@MuhammadRabi Assigned to you
