### ISSUE TITLE
[FEAT]: add a small description in the main readme.md file

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#14]
Add the following :
-link to the CONTRIBUTORS.md file 
-a small description thanking all your contributors

**Comment by MuhammadRabi** [comment]
Hi Arslan, I'd love to work on this issue.

**Comment by ArslanYM** [comment]
@MuhammadRabi Assigned to you.

**Comment by ArslanYM** [comment]
Completed
