### ISSUE TITLE
⭐FEAT: Click on more details should go to user github profile

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#141]
# TODO:
- The user should be able to go to user profile after clicking on more details 
- 
![Screenshot 2023-05-28 235238](https://github.com/ArslanYM/StarterHive/assets/104521101/c7fa6acf-90eb-417a-a905-6f9779cf372d)

**Comment by amratansh12** [comment]
Assign me please, I am interested to work upon this.

**Comment by ArslanYM** [comment]
Assigned to you @amratansh12

**Comment by amratansh12** [comment]
Thanks @ArslanYM  and PR raised!

**Comment by ArslanYM** [comment]
Fixed  in #142
