### ISSUE TITLE
[BUG]: Correction in the steps to contribute in the main Readme.md file

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#15]
After the  4th step there should be another step where you ask the contributor to : 

``` 
Make the changes 

```
## Refer
![issue](https://github.com/ArslanYM/StarterHive/assets/104521101/953b378d-ecc5-4544-9ad9-3aac376d4a82)

**Comment by nadeem099** [comment]
I will make this change @ArslanYM.
and I think there is some changes needed under section "Other points to remember while submitting your work:"

For points 1 & 3 space in folder name is not needed, and will we follow snake case?  in React mostly I see Pascal case for component names and camel case of js files.

For point 2 file extensions .py .c and .cpp. I don't think we will use cpp.

I will change these as part of the this issue.

**Comment by ArslanYM** [comment]
> I will make this change @ArslanYM. and I think there is some changes needed under section "Other points to remember while submitting your work:"
> 
> For points 1 & 3 space in folder name is not needed, and will we follow snake case? in React mostly I see Pascal case for component names and camel case of js files.
> 
> For point 2 file extensions .py .c and .cpp. I don't think we will use cpp.
> 
> I will change these as part of the this issue.

Nadeem im glad that you pointed out these issues. I would rather suggest opening a new issue for each of these problems , that way we can help this project stay structured. You can raise those issues induvidually and I will assign them to you. As for this issue, Making the above mentioned details would be sufficient. Thankyou

**Comment by VarunJoshi10** [comment]
@ArslanYM 
Can you assign this issue to me?
I will update the README.MD as per requirement.

**Comment by ArslanYM** [comment]
@nadeem099 you can start working on this.

**Comment by ArslanYM** [comment]
Completed!
