### ISSUE TITLE
🔴 BUG: logo not aligned.

### ISSUE THREAD

**Issue by rahilansari261** [ArslanYM/StarterHive#154]
1 Logo at header is not aligned with text below in hero section
tip: removing margin left will do the work for bug 1

**Comment by shaikahmadnawaz** [comment]
I am working on this issue @ArslanYM

**Comment by rahilansari261** [comment]
Any updates?

**Comment by rahilansari261** [comment]
> I am working on this issue @ArslanYM 

Any update?

**Comment by ArslanYM** [comment]
> > I am working on this issue @ArslanYM 
> 
> Any update?

He had raised a PR which has merge conflicts, there was no response from him. And the PR also had deployment issues. So I had to close the PR due

**Comment by rahilansari261** [comment]
> > > > I am working on this issue @ArslanYM
> > > 
> > > 
> > > Any update?
> > 
> > He had raised a PR which has merge conflicts, there was no response from him. And the PR also had deployment issues. So I had to close the PR due
> 
> I was in college, Okay.

Do you need any help you can ask here.
I saw your PR you made the changes right 👍🏼 but as @ArslanYM said it had conflicts so i believe you need to reconsider looking at the PR guide you can find that in readme of the project .

**Comment by shaikahmadnawaz** [comment]
Okay, Thank you.

**Comment by rahilansari261** [comment]
fixed here https://github.com/ArslanYM/StarterHive/pull/182
