### ISSUE TITLE
⭐FEAT: Add logo to header 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#156]
# TODO: 
- Add the logo and remove the star ✨
- Logo : https://github.com/ArslanYM/StarterHive/blob/main/web/public/hive.svg
- Here:
![header (2)](https://github.com/ArslanYM/StarterHive/assets/104521101/3a12b505-a650-4d11-a2bc-bcb2c4fe6b8d)

**Comment by Nura-mohamed** [comment]
can I try working on this?

**Comment by ArslanYM** [comment]
@Nura-mohamed Any progress?

**Comment by GFerreiroS** [comment]
Hi, I already done it here is the pull request, [#180](https://github.com/ArslanYM/StarterHive/pull/180)

**Comment by ArslanYM** [comment]
Merged. Thankyou for your contribution @GFerreiroS

**Comment by vishalsingh2972** [comment]
@ArslanYM I see a PR is already been merged so can you close this issue!
