### ISSUE TITLE
🔴 BUG: 404 NOT_FOUND

### ISSUE THREAD

**Issue by masif2002** [ArslanYM/StarterHive#158]
## Description
A 404 Error when tried to navigate to a page directly by URL. 
Try this: https://starter-hive.vercel.app/contributors

![image](https://github.com/ArslanYM/StarterHive/assets/94846379/6bb0982b-8abc-4e22-a69f-28c3cfb6289f)

### Additional context
* This is probably due to the routing on server side 
* We need to add a redirect rule to route back to the root URL `/` regardless of the route entered

**Comment by ArslanYM** [comment]
@masif2002 do you wanna work on this?

**Comment by masif2002** [comment]
Sure @ArslanYM

**Comment by masif2002** [comment]
@ArslanYM #160 didn't seem to fix the issue. I think we need to move `vercel.json` to the web directory

**Comment by ArslanYM** [comment]
Lemme do it @masif2002

**Comment by masif2002** [comment]
> Lemme do it @masif2002

Sure

**Comment by ArslanYM** [comment]
done , Give it a look now

**Comment by masif2002** [comment]
Awesome. It's fixed now!

**Comment by ArslanYM** [comment]
Cool @masif2002 !!
