### ISSUE TITLE
⭐FEAT: Loader Component for contributors page

### ISSUE THREAD

**Issue by masif2002** [ArslanYM/StarterHive#162]
## Feature Request
A loader component for the [contributors page](https://starter-hive.vercel.app/contributors) would be cool. Even though the results fetched are pretty quick, it can take up to a maximum of one to two seconds for it to complete. 

![image](https://github.com/ArslanYM/StarterHive/assets/94846379/59efc652-250f-436f-b60f-b9e1d4a971a3)
![image](https://github.com/ArslanYM/StarterHive/assets/94846379/0943a3e4-dd45-467d-85c5-996cc920477c)

### Proposal
* A loader component to be added

**Comment by masif2002** [comment]
I would like to work on this, if the feature is planned on being added to the project

**Comment by ArslanYM** [comment]
yeah sure! I was planning for something like this too. COOL!!
