### ISSUE TITLE
[BUG] License image is not loading in the README.md

### ISSUE THREAD

**Issue by nadeem099** [ArslanYM/StarterHive#17]
**Describe the bug**
License image is not loading the README.md because of incorrect path.

**Screenshots**
![readme](https://github.com/ArslanYM/StarterHive/assets/55915789/aee964a6-a099-4c31-a9dd-d4fbb458d47c)

**Comment by ArslanYM** [comment]
@nadeem099  Would you like to work on this issue?

**Comment by nadeem099** [comment]
Sure, please assign

**Comment by ArslanYM** [comment]
@nadeem099 The issue still exists 
![Screenshot 2023-05-13 201006](https://github.com/ArslanYM/StarterHive/assets/104521101/aceacb57-f9b6-4a72-89d9-41940f1941c1)

**Comment by ArslanYM** [comment]
Fixed
