### ISSUE TITLE
⭐FEAT: Update the table of  contents in main Readme 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#173]
# TODO:
- Update the main readme file as per new changes  introduced
- go through the readme file and check what changes have been made and include those section in the table of contents
![new](https://github.com/ArslanYM/StarterHive/assets/104521101/26766970-087d-4dd2-a4e2-256b997b3a58)
- For example - Frontend development section was introduced etc. add Frontend Dev to table of contents

**Comment by StephenCahillane** [comment]
Hey I think I am up for this task, can I give it a try?

**Comment by ArslanYM** [comment]
Hey @StephenCahillane  , this issue has been resolved in #176
