### ISSUE TITLE
⭐FEAT: Make the Readme well organized and easy to read

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#174]
# TODO : 
- In the main Readme file , look for ways to make the Readme more concise or better looking. 
-  The markup language used doesnt look well organized and same throughout

**Comment by AshwanthramKL** [comment]
Hey @ArslanYM, can I try my hand at this?

**Comment by ArslanYM** [comment]
@AshwanthramKL please do🫱🏻‍🫲🏼🫱🏻‍🫲🏼
