### ISSUE TITLE
🔴 BUG: home page need to change for some mobile devices 

### ISSUE THREAD

**Issue by rahilansari261** [ArslanYM/StarterHive#179]
The home page in some mobile devices is Little weird

- Header/ navbar wraps it should be in one line no-wrap

- The hero section text is also having so much white space 

- and floating divs looked squeezed in mobile devices

![Screenshot_2023-06-01-08-56-34-87_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/ArslanYM/StarterHive/assets/12849916/0af33668-71eb-4e6a-8e46-d88e95ed399f)

**Comment by rahilansari261** [comment]
@ArslanYM need your input.
Hero text has 4 lines we can make it upto 3 lines only for mobile devices  📱
For floating divs we can have only two columns instead of going with 3 column in 📱 mobile devices for medium to any sizes it's fine 👍🏼

**Comment by ArslanYM** [comment]
> @ArslanYM need your input.
> Hero text has 4 lines we can make it upto 3 lines only for mobile devices  📱
> For floating divs we can have only two columns instead of going with 3 column in 📱 mobile devices for medium to any sizes it's fine 👍🏼
> 
> 

Yes I noticed this too yesterday. Great advice, we can proceed with that. Would you like to work on it? I think the header starting behaving like this after we changed the text to bold. But lets see.

**Comment by rahilansari261** [comment]
assign it to me.
I think for mobile devices we don't need bold font .

**Comment by ArslanYM** [comment]
Fixed in #182
