### ISSUE TITLE
[BUG] The link to the coding style doesn't land into a valid website

### ISSUE THREAD

**Issue by tanbirali** [ArslanYM/StarterHive#19]
**Describe the bug**
The hyperlink for the coding style in reading.md does not land into a valid website

**Expected behavior**
The hyperlink should land into a valid website

**Screenshots**
![Screenshot (80)](https://github.com/ArslanYM/StarterHive/assets/124070023/e6ca26c8-61c1-4fb6-af70-ab76b3ced61e)

**Comment by ArslanYM** [comment]
@Sohoxic Could you provide the correct link for this? Then @tanbirali can start working on it

**Comment by Beast-Monk** [comment]
Hi, there is an trailing Quotation mark (") or its equivalent (%22) in the hyperlink URI.
I have corrected that and shared a PR: [#83](https://github.com/ArslanYM/StarterHive/pull/83).

Btw, I have a question : Since this is a styling guide for Python, are you sure this is the intent for the hyperlink ?
Kindly review @ArslanYM & @tanbirali, this is my first Open-source PR ! 
:)

**Comment by ArslanYM** [comment]
@Beast-Monk I have merged the PR since it was your first one!! Congratulations. 
Yet, I would love to change it from python to Javascript coding style. Can you make the changes?

**Comment by ArslanYM** [comment]
> There are the 3 styling guides I found :
> 
> **AirBnB Style guide (JS/React)** : https://github.com/airbnb/javascript **Google Style guide (JS)** : https://google.github.io/styleguide/jsguide.html **Khan Academy Style guide (React)** : https://github.com/Khan/style-guides/blob/master/style/react.md#open-elements-on-the-same-line
> 
> I believe AirBnB one is a comprehensive one as we have style guides for all frontend (JS/React/Css in JS/SAAS) in the same repo.
> 
> For the Google style guide, it is already in the Hyperlink @line-no:31 "style guides", within its combined style guide repo.
> 
> Lets vote for the preference, I vote for AirBnB one ! [Also, please assign this issue to me]

I vote for the same. 
Great research.
 Assigned to you.
