### ISSUE TITLE
[BUG] Changes needed under section "Other points to remember while submitting your work:" of README.md

### ISSUE THREAD

**Issue by nadeem099** [ArslanYM/StarterHive#20]
**In README.md under section "Other points to remember while submitting your work:"**

For points 1 & 3; space in folder name is not needed, and will we follow snake_case? in React mostly we uses PascalCase for component names and camelCase of js files.

For point 2; file extensions .py .c and .cpp. It needs to be changed to .js, .jsx, .css

**Comment by ArslanYM** [comment]
@nadeem099 Assigned to you. Thankyou

**Comment by ArslanYM** [comment]
Completed!
