### ISSUE TITLE
🔴 BUG: project name has left margin 

### ISSUE THREAD

**Issue by rahilansari261** [ArslanYM/StarterHive#202]
In the header project name has left margin it should be removed. ![IMG_20230603_203143.jpg](https://github.com/ArslanYM/StarterHive/assets/12849916/eda41086-ac46-4589-b04a-48476b1609ac)

**Comment by MuhammadRabi** [comment]
I can do this if it is still available.

**Comment by ArslanYM** [comment]
@rahilansari261 Would you like this work on this?

**Comment by rahilansari261** [comment]
Ok I'll fix it

**Comment by lokeshkadem** [comment]
i would love to work on this
