### ISSUE TITLE
FEAT: Clicking on Footer icon doesn't navigate to home

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [ArslanYM/StarterHive#209]
Hey, While clicking on footer icon, It doesn't navigating us to Home.
I'd like to fix this issue.
Could you please assign this to me.

**Comment by ArslanYM** [comment]
@SoundaryaKoutharapu, Would you like to add this feature to the project. Seem pretty straight forward.

**Comment by FaizanMuhammadSE** [comment]
@ArslanYM, assign this issue to me

**Comment by SoundaryaKoutharapu** [comment]
@ArslanYM Yep, I would like to work on this.

**Comment by ArslanYM** [comment]
@FaizanMuhammadSE , @SoundaryaKoutharapu seems to work on this issue. And since she has raised it, I will be assigned this issue to her.

**Comment by SoundaryaKoutharapu** [comment]
@ArslanYM will start working on the issue.

**Comment by SoundaryaKoutharapu** [comment]
@ArslanYM Could you please tell me how to run the project
Should I use (npm install & npm start)

**Comment by ArslanYM** [comment]
Fixed in #212
