### ISSUE TITLE
⭐FEAT: Add yellow color to `Find issues` button in light mode and default in dark mode..

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#213]
# Todo:
- Add yellow theme color to find issues button in light mode and the default purple in dark mode. 

![1](https://github.com/ArslanYM/StarterHive/assets/104521101/8d6817ff-0e38-43ba-8749-3904ad554d9c)

**Comment by ThGnommy** [comment]
hello! I'd like to work on this one 🙂

**Comment by ArslanYM** [comment]
> hello! I'd like to work on this one 🙂

Assigned to you.

**Comment by harshdaslaniya** [comment]
hii , I want to work on this issue

**Comment by ArslanYM** [comment]
Light mode has been removed.
