### ISSUE TITLE
⭐FEAT: Add Github icon only to navigate to github repo

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#214]
# TODO:
- Instead of having a github button , add an icon that navigates to github repo.. 
- Make its  border color dynamic for dark and light mode.
![2](https://github.com/ArslanYM/StarterHive/assets/104521101/e9f1592a-bced-4366-8d14-45c1f76b7133)

**Comment by MuhammadRabi** [comment]
I would like to work on this @ArslanYM

**Comment by ArslanYM** [comment]
@MuhammadRabi Sure thing. Assigned to you.

**Comment by MuhammadRabi** [comment]
@ArslanYM  Please give me feedback on these results before the PR

  <img src="https://imgtr.ee/images/2023/06/05/bC6nr.png" alt="License">
<img src="https://imgtr.ee/images/2023/06/05/bC5RY.png" alt="bC5RY.png" border="0" />

**Comment by ArslanYM** [comment]
@MuhammadRabi Looks like you've just removed the text and arrow. You need to keep an svg icon or icon that has some hover effects and is dynamic for light/dark mode. Only the github icon. No need for button

**Comment by ArslanYM** [comment]
@MuhammadRabi Please provide mockups before raising a PR.

**Comment by MuhammadRabi** [comment]
> @MuhammadRabi Please provide mockups before raising a PR.

no problem, what would you like to change here?

<img src="https://imgtr.ee/images/2023/06/07/pWSXx.png" alt="pWSXx.png" border="0" />

**Comment by ArslanYM** [comment]
Like I said earlier, just an svg icon(dynamic color for light/dark)  would suffice. You can see in the above picture there is a button around the github svg, which needs to be removed.

**Comment by ArslanYM** [comment]
No, Rather something like this.
for dark 
![thisdark](https://github.com/ArslanYM/StarterHive/assets/104521101/ca06d173-ab14-4f64-a0a0-ff364d8aaa72)
for light
![this](https://github.com/ArslanYM/StarterHive/assets/104521101/ac20da3d-b92b-4668-a241-e12e58107e4d)


Or something better. But the idea is this

**Comment by ArslanYM** [comment]
An increase in size on hover would do, Also these look similar to what I sent above. I would love to see some other options as well.

**Comment by MuhammadRabi** [comment]
I think the btn were the best option, we can make it a square icon, 

you may like those 

<img src="https://imgtr.ee/images/2023/06/07/phaMA.png" alt="phaMA.png" border="0">
<img src="https://imgtr.ee/images/2023/06/07/ph8s7.png" alt="ph8s7.png" border="0">

**Comment by ArslanYM** [comment]
A svg would suffice. No need for borders.

**Comment by abhisheksharma886** [comment]
Hello, I would like to work on this, can it be assigned to me

**Comment by ArslanYM** [comment]
@abhisheksharma886 This has been resolved. Thankyou
