### ISSUE TITLE
⭐FEAT: Navbar into  hamburger with drawer

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#217]
# TODO:
- For small screen devices the navbar should have one hamburger menu with drawer in the left , LOGO in the middle , and  github button + light/dark toggle on the right. 
- Refer : [THIS](https://tailwindcomponents.com/component/navbar-hamburger-menu/landing)

![navbar](https://github.com/ArslanYM/StarterHive/assets/104521101/41a0663b-e0ca-48da-a616-b2c32816ef3c)

**Comment by Aryan123-rgb** [comment]
@ArslanYM Would like to work on this issue

**Comment by ArslanYM** [comment]
Sure, would love to discuss more about this. Raise a discussion for any doubts before raising a PR. Assigned to you.

**Comment by ArslanYM** [comment]
@Aryan123-rgb No progress?

**Comment by yacdanyCR** [comment]
@ArslanYM  assign this feature to me

**Comment by ArslanYM** [comment]
> @ArslanYM  assign this feature to me

@yacdanyCR Assigned to you.

**Comment by yacdanyCR** [comment]
@ArslanYM what about this

![Screenshot from 2023-06-16 09-33-08](https://github.com/ArslanYM/StarterHive/assets/77762960/04c5a05e-a4ef-4321-9692-2741c287d497)
![Screenshot from 2023-06-16 09-33-12](https://github.com/ArslanYM/StarterHive/assets/77762960/11c2071b-71c5-452e-be22-3fe9382960a7)

**Comment by ArslanYM** [comment]
the navbar should collapse towards the left into a hamburger. Also the on click effect is not necessary.

**Comment by yacdanyCR** [comment]
@ArslanYM  like this .?

![Screenshot from 2023-06-16 12-03-59](https://github.com/ArslanYM/StarterHive/assets/77762960/e804deef-a4e5-417b-8115-a90398eb412f)

**Comment by ArslanYM** [comment]
I mean the hamburger button should be placed on the left side.

**Comment by Tejsvapandey1** [comment]
would you like to assign me the work

**Comment by ArslanYM** [comment]
@Tejsvapandey1 This has been fixed.
