### ISSUE TITLE
⭐FEAT: Enhance UI of the DOCS section

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#218]
# TODO:
- Enhance the ui and content of DOCS section of the project.
- Add new images and better UX to the page. 
![Screenshot 2023-06-05 234647]

- Refer : https://starter-hive.vercel.app/docs

**Comment by Shubh8899** [comment]
I would like to work on this one.

**Comment by ArslanYM** [comment]
I would definitely like to have a discussion about what you have in mind about this. Raise a discussion in the discussion section of this project. I will be assigning you after we talk.

**Comment by Shubh8899** [comment]
Started a discussion #240, please review.

**Comment by ArslanYM** [comment]
Sure

**Comment by yashwanth-gh** [comment]
Hey can you assign me this

**Comment by ArslanYM** [comment]
> Hey can you assign me this

This issue is resolved.
