### ISSUE TITLE
🔴 BUG: Loader not visible for light theme

### ISSUE THREAD

**Issue by masif2002** [ArslanYM/StarterHive#225]
## Description
Loader not visible for light theme

### Dark Theme
![image](https://github.com/ArslanYM/StarterHive/assets/94846379/1c1842e8-93b2-4a47-88e1-05c8eba9e49a)

### Light Theme
![image](https://github.com/ArslanYM/StarterHive/assets/94846379/cfe97404-6a39-450b-9e34-e3176e193dc0)

## Expected behavior
Color of the Loader component to be dark

**Comment by masif2002** [comment]
I would like to work on this

**Comment by ArslanYM** [comment]
Sure thing , Assigned to you.
