### ISSUE TITLE
[FEAT]: Migrate the issues section from Readme.md file to a separate file for now.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#23]
Move this content to a separate file. (eg issues.md). Store that file in a directory names ISSUES.

![s](https://github.com/ArslanYM/StarterHive/assets/104521101/9f361574-68cf-4440-87c5-bc7e876e81f6)

**Comment by VarunJoshi10** [comment]
@ArslanYM assign this issue to me.
I will create a separate directory for issue and add a issues.md in it.
should I have to create a new request to link the good first issue to it ? or i can do it in this only.

**Comment by ArslanYM** [comment]
> @ArslanYM assign this issue to me.
> 
> I will create a separate directory for issue and add a issues.md in it.
> 
> should I have to create a new request to link the good first issue to it ? or i can do it in this only.

I would suggest creating a new issue for the next step. Thankyou

**Comment by ArslanYM** [comment]
Fixed in #24
