### ISSUE TITLE
⭐FEAT: Add link to labels on the issue card

### ISSUE THREAD

**Issue by tim87henry** [ArslanYM/StarterHive#232]
Currently, the issue card displays a list of labels for each issue. But, this is just text and doesn't lead to anything.  I think it would be nice if the issue card's labels were links, to the corresponding GitHub label page, for this project. 
Example: A label called "hold" could open the page https://github.com/ArslanYM/StarterHive/labels/hold

**Comment by tim87henry** [comment]
If it's okay to add this modification, I would like to work on this.

**Comment by ArslanYM** [comment]
> If it's okay to add this modification, I would like to work on this.

Sure thing , assigned to you.
