### ISSUE TITLE
⭐FEAT: Add custom scrollbar

### ISSUE THREAD

**Issue by masif2002** [ArslanYM/StarterHive#233]
## Add custom scrollbar
* Would love to see a custom scroll-bar instead of the default ones
* The current scrollbar looks like this

    ![image](https://github.com/ArslanYM/StarterHive/assets/94846379/9608bd90-7574-4fd0-8520-afbd8c064fb7)

**Comment by rahilansari261** [comment]
Let me give it a try

**Comment by ArslanYM** [comment]
@rahilansari261 Assigned to you.

**Comment by mdfaizalam555** [comment]
@masif2002 please assign me , I want to work on this issue
