### ISSUE TITLE
⭐FEAT: The light/dark toggle isnt itself dynamic

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#243]
# TODO:
- The light/dark mode toggle on header should itself become light colored when swtiched to light mode and default dark when switched to dark mode.
- Keep the color theme matching to the project theme.
- THIS:
![1](https://github.com/ArslanYM/StarterHive/assets/104521101/16b5641a-7e16-473c-9aed-945040e5346e)

**Comment by MuhammadRabi** [comment]
If you like this mockup, let me work on it.

<img src="https://imgtr.ee/images/2023/06/12/QQxo4.png" alt="light"/>

**Comment by Aswin-Inigo** [comment]
I would like to work on this issue.. Will you let me working on this

**Comment by ArslanYM** [comment]
> @ArslanYM If you like this mockup, let me work on it.
> 
> [![QQcDB.png](https://camo.githubusercontent.com/26fb53f69cb02513f7a7c7a3b0d9484e7f63f11c407aac28e6bb36274a4b1f35/68747470733a2f2f696d6774722e65652f696d616765732f323032332f30362f31322f51516344422e706e67)](https://imgtr.ee/i/QQcDB)

More light would suit the button. Keep the toggle button white and inside some shade of grey.

**Comment by pradnyabhukan** [comment]
Can I work on this one?

**Comment by PradnyaB17** [comment]
Can i work on this one?

**Comment by ArslanYM** [comment]
@PradnyaB17 The toggle will be removed in the next few PRs. This issue will be removed as well. You can find other issues to work on.
