### ISSUE TITLE
⭐FEAT: The github svg on navbar animation 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#244]
# TODO: 
- The github svg on header should have a small change in size rather than becoming large. 
- It should become a little bigger but not too big like it is doing right now.
- ![2](https://github.com/ArslanYM/StarterHive/assets/104521101/06b51a30-2b3b-4510-b165-b5d329f28aa0)

**Comment by AshwanthramKL** [comment]
@ArslanYM Do you want it to scale less?

**Comment by ArslanYM** [comment]
Yeah @AshwanthramKL

**Comment by AshwanthramKL** [comment]
I'll try my hand at it then

**Comment by ArslanYM** [comment]
Fixed in #281
