### ISSUE TITLE
⭐FEAT: Navbar navigation items hover effect

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#245]
# TODO:
- The navbar navigation items should have a hover effect which is same as the effect it has right now when clicked on it. 
- The same should be on hover as well. 

![onhover](https://github.com/ArslanYM/StarterHive/assets/104521101/dd434297-86e2-4061-a896-27649c6b1ff8)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue

**Comment by Sivasish48** [comment]
I would love to contribute to this issue . Can I be assigned to this one?

**Comment by ArslanYM** [comment]
> I'd like to work on this issue

Sure thing , Assigned to you.

**Comment by harshsbhandari** [comment]
Hello @ArslanYM, I have solved this issue already, can you please assign this to me.

**Comment by ArslanYM** [comment]
@harshsbhandari were you assigned to this issue?

**Comment by harshsbhandari** [comment]
I am not assigned this issue

**Comment by ArslanYM** [comment]
> I am not assigned this issue

It's written in the guidelines to not start working on any issue without getting assigned to it. Please read the contribution guide before contributing to this project.

**Comment by harshsbhandari** [comment]
Hey @ArslanYM if there are no developments on this issue, so can you please assign it to me

**Comment by tarunsamanta2k20** [comment]
@harshsbhandari iam working

**Comment by PawanAK** [comment]
I would love to contribute to this issue . Can I be assigned to this one?

**Comment by ArslanYM** [comment]
@PawanAK Sure thing , Assigned to you.

**Comment by harshsbhandari** [comment]
Can this issue be assigned to me too?

**Comment by ArslanYM** [comment]
Sure @harshsbhandari , You can start working on this. This should be pretty straight forward.

**Comment by ratishjain12** [comment]
@ArslanYM is the issue resolved if not can you assign it to me?

**Comment by rajanarahul93** [comment]
I am interested in taking on the task at hand and want to assure you that I will complete it to the best of my ability. I kindly request that you assign this task to me

**Comment by ArslanYM** [comment]
fixed
