### ISSUE TITLE
🔴 BUG: Nav text for medium devices

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#249]
**Describe the bug**
the navbar/header navigation buttons text is not bold for medium devices

**To Reproduce**
1. Go to 'starterhive'
2. Decrease the size of window till medium width

**Expected behavior**
should be bold

**Screenshots**
![for](https://github.com/ArslanYM/StarterHive/assets/104521101/0596a9e0-3cb8-44ab-8fc7-234d852edb95)

**Additional context**

**Comment by prasenjitpawar22** [comment]
@ArslanYM, can I work on this? Also, should the font be bold on smaller devices as well?

**Comment by ArslanYM** [comment]
@prasenjitpawar22 Yes the font should be bold for smaller devices as well. Assigned to you.
