### ISSUE TITLE
⭐FEAT: Filter

### ISSUE THREAD

**Issue by turtlebeasts** [ArslanYM/StarterHive#254]
**Problem: Mixed up issue status**
All the cards in the 'issues' route are jumbled and it is very hard to find a specific type of issue with our desired issue status. Ex: if I'm looking for issues that are open, then I have to manually go through each card and look for the status manually.

**Solution: Filter**
This hard work can be solved by adding a filter feature on the page. An issue has three status: open, closed, assigned. The filter is a simple select element, which will have these three options to filter according to what we are looking for.

**Preview**
I've sent a PR please check it out here [Filter#253](https://github.com/ArslanYM/StarterHive/pull/253)

![pull_req_253](https://github.com/ArslanYM/StarterHive/assets/52573759/337e022b-10c2-46d8-aef5-594ba6170fdc)

**Comment by ArslanYM** [comment]
Fixed in #253
