### ISSUE TITLE
⭐FEAT: filter button enhancement. 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#257]
**Is your feature request related to a problem? Please describe.**
The filter button doesnt look good rn.

**Describe the solution you'd like**
enhance the UI of the the filter button.

![Screenshot 2023-06-18 225054](https://github.com/ArslanYM/StarterHive/assets/104521101/a166d27e-e129-4e80-a23d-c60fec9d862f)

**Comment by shyamtawli** [comment]
Any specific design you would like to share?

**Comment by ArslanYM** [comment]
@shyamtawli  Assigned to you.

**Comment by Pushpajit** [comment]
Can you please describe few details about what kind of design you want to implement, because I have few designs in my mind and want to work on this feature, you can assign it to me also.

**Comment by ArslanYM** [comment]
Fixed
