### ISSUE TITLE
⭐FEAT: Search bar

### ISSUE THREAD

**Issue by turtlebeasts** [ArslanYM/StarterHive#259]
**Feature: Search bar**

A search bar is need to search through the contributors list. 

**Example**

![image](https://github.com/ArslanYM/StarterHive/assets/52573759/8228eaab-f110-4103-8ca2-2135a2447b28)

![image](https://github.com/ArslanYM/StarterHive/assets/52573759/6302be80-1379-434c-a291-ae83a2d39021)

**SOLVED**

A PR has already been sent that implements this feature, please refer to this [PR](https://github.com/ArslanYM/StarterHive/pull/260)

**Comment by ashishratre404** [comment]
could you assign this to me?
