### ISSUE TITLE
🔴 BUG: Header / Navbar alignment spacing issue

### ISSUE THREAD

**Issue by rahilansari261** [ArslanYM/StarterHive#266]
Header / Navbar alignment spacing issue 

The header needs to be redesigned to look better on the mobile as it is not aligned properly and on the web it has spacing around it and not aligned with below hero section.

Header should be between these two lines perfectly aligned with below hero section 
![Screenshot_2023-06-20-20-46-16-42_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ArslanYM/StarterHive/assets/12849916/5c53a01c-9485-4155-9a28-436ce02b3082)

And in this second image for mobile devices the logo should be aligned properly with other elements as well
![Screenshot_2023-06-20-20-45-22-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/ArslanYM/StarterHive/assets/12849916/4ba529c5-15d3-4f35-b958-f4edf447e121)

**Comment by ArslanYM** [comment]
@rahilansari261 Would you like to work on this issue?

**Comment by rahilansari261** [comment]
Ok assign it to me.

**Comment by ArslanYM** [comment]
Assigned to you.
