### ISSUE TITLE
🔴 BUG: decrease the size of search bar 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#270]
**Describe the bug**
The size of search bar is too big. 

**Expected behavior**
Reduce the width of the search bar to be in the middle.
**Screenshots**
![size](https://github.com/ArslanYM/StarterHive/assets/104521101/5ac71d13-2e9a-49f0-90fd-043b605fa3af)

**Comment by farhadjaman** [comment]
hey there. I can resolve this issue.If you kindly assign it to me I will start working.

**Comment by KarthikShetty5** [comment]
hey i will solve this issue , can u assign me

**Comment by farhadjaman** [comment]
@KarthikShetty5 i asked him to assign the issue to me first.

**Comment by KarthikShetty5** [comment]
> @KarthikShetty5 i asked him to assign the issue to me first.

let me see

**Comment by ArslanYM** [comment]
@KarthikShetty5 Please don't start working on the issue without getting assigned to it.

**Comment by ArslanYM** [comment]
@farhadjaman As per the rules of this project, This issue will be assigned to you.

**Comment by farhadjaman** [comment]
Thank you.on it!

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by ArslanYM** [comment]
@Pulkitxm This issue has already been assigned to someone. Look for other issues to work on

**Comment by farhadjaman** [comment]
hello, the package.json file is missing in the GitHub file, can you kindly direct me to how  set up the project.

**Comment by ArslanYM** [comment]
@farhadjaman web/README.md Read these guidelines carefully

**Comment by farhadjaman** [comment]
@ArslanYM I have made a PR. Would you kindly review it?

**Comment by Benedict-Kpaduwa** [comment]
Hey, can you assign me this issue, seems it hasn't been fixed

**Comment by ArslanYM** [comment]
Sure thing. Assigned to you.

**Comment by joshuasoftdev** [comment]
Can I please be assigned to this @ArslanYM

**Comment by PawanAK** [comment]
Can I please be assigned to this @ArslanYM

**Comment by ArslanYM** [comment]
@PawanAK This issues is resolved. Thankyou.

**Comment by Ayoubrabiae** [comment]
@ArslanYM 
I think the appearance of the search bar on the phone is still unsatisfactory. It looks like this 👇🏼👇🏼👇🏼
making it difficult to see the words we type, resulting in a poor user experience.

![SearchBarBug](https://github.com/ArslanYM/StarterHive/assets/105998148/f0dd41e9-b88b-443d-afd5-6aa406caac75)

I can fix it now if you want

**Comment by ArslanYM** [comment]
@Ayoubrabiae  Please go ahead.

**Comment by Ayoubrabiae** [comment]
I think the issue has been resolved for now.

**Comment by kumar2023jha2000** [comment]
can i work on this issue if no one is working

**Comment by ArslanYM** [comment]
@kumar2023jha2000 This issue has been resolved
