### ISSUE TITLE
🔴 BUG: Enhance Code Scalability through Refactoring

### ISSUE THREAD

**Issue by ashishratre404** [ArslanYM/StarterHive#278]
**Describe the bug**
 I noticed that we have a navigation menu section where the menu items are hard-coded. This approach could lead to redundant code and make it challenging to scale the menu in the future.

**Screenshot**
![menu-before](https://github.com/ArslanYM/StarterHive/assets/78258094/de778a30-d1f4-43a5-b9a8-e1bd16424702)

**Expected behavior**
To address this, I propose refactoring the code by introducing a more flexible and scalable solution. We can define an array of menu items as constants, each containing the title and corresponding path. By iterating over this array, we can dynamically generate the menu items, eliminating the need for repetitive code.

**Screenshots**
![menu-items](https://github.com/ArslanYM/StarterHive/assets/78258094/13169114-f9e0-44a9-ba60-fb0427c0261f)
![menu-after](https://github.com/ArslanYM/StarterHive/assets/78258094/ae41b8ac-3b72-4f0b-b48c-c5254d804844)

**Comment by ThGnommy** [comment]
can you upload the images again? I think their links are broken

**Comment by ashishratre404** [comment]
Uploaded images again, it should work now.

**Comment by ashishratre404** [comment]
I have already completed the task and I am currently awaiting the approval of the maintainer. Once I receive their approval, I will proceed to submit a PR for the changes. @ArslanYM

**Comment by ArslanYM** [comment]
@ashishratre404 Looks like a great enhancement. You can proceed with this.

**Comment by ashishratre404** [comment]
This issue has been resolved
