### ISSUE TITLE
[BUG]: fix the issues section

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#30]
Make the issues section better formatted.

![issues](https://github.com/ArslanYM/StarterHive/assets/104521101/0b2af729-bb0b-4385-b23c-5da11b8bb01b)

**Comment by Csrivastava003** [comment]
I would like to work on this.

**Comment by ArslanYM** [comment]
@Csrivastava003 Suree!!! Assigned to you.

**Comment by ArslanYM** [comment]
@Csrivastava003 Any progress?

**Comment by ArslanYM** [comment]
Fixed
