### ISSUE TITLE
⭐FEAT: Styling the search bar and scrollbar.

### ISSUE THREAD

**Issue by kaur-rajdeep** [ArslanYM/StarterHive#300]
**Is your feature request related to a problem? Please describe.**
-The search bar isn't too good looking, and the alignment of it isn't proper, the margin on top is more than bottom. 
-The scrollbar need to be enhanced.

**Describe the solution you'd like**
-I would like to add some styles and icon in the searchbar
-I would like to add some styles to the scrollbar as well.

Could you please assign me this issue, I would like to work on it.

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/ArslanYM/StarterHive/assets/106001705/f2a3fcb3-a7b1-45bd-aaa5-a9dbc273bc26)
Thanks

**Comment by ArslanYM** [comment]
@kaur-rajdeep Sure thing , You can proceed. Make sure you read the project Guidelines and Contributing Guidelines well. Thankyou

**Comment by inbuilt-aura** [comment]
@ArslanYM Hey, can i work on this issue?

**Comment by ArslanYM** [comment]
@inbuilt-aura This issue is closed.
