### ISSUE TITLE
⭐FEAT: Improve light theme for the project

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#309]
# TODO: 
- Would love to see new UI/UX designs for the project's light mode 
- Provide prototypes for the light theme before raising a PR

**Comment by jainampatel22** [comment]
What kind of Ui/Ux you would love to see ? I am highly interested for this . Can you assign this to me

**Comment by ArslanYM** [comment]
I would love to see what you have in mind for the light theming of this project. You can try it out on your local development server  and provide the screenshots and then we can proceed.

**Comment by Yuroq** [comment]
Hey! Did this get solved?

**Comment by ArslanYM** [comment]
@Yuroq No, I have decided to remove light theme because this issue has been not worked on for a long time. If you can make the light theme better , we can keep it otherwise we will be removing it soon.

**Comment by GD0910** [comment]
> @Yuroq No, I have decided to remove light theme because this issue has been not worked on for a long time. If you can make the light theme better , we can keep it otherwise we will be removing it soon.

hey is this issue still open 
shall i try for improving light mode

**Comment by ArslanYM** [comment]
Light mode has been removed from the project.
