### ISSUE TITLE
[BUG] add some margin to the navbar links

### ISSUE THREAD

**Issue by karthiknadar1204** [ArslanYM/StarterHive#313]
### Description of the bug

Add some margin to the navbar links, they look awfully close, adding some spacing would bring out the hover effects even more

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [X] I am willing to work on this issue (optional)

**Comment by karthiknadar1204** [comment]
I would like to work on this issue

**Comment by Vidhanvyrs** [comment]
hey @karthiknadar1204  I would like to contribute on this issue. Please assign this to me

**Comment by ArslanYM** [comment]
@karthiknadar1204 Can you add some screenshots of what exactly we are talking about here?

**Comment by karthiknadar1204** [comment]
<img width="633" alt="Screenshot 2023-08-23 at 7 44 07 PM" src="https://github.com/ArslanYM/StarterHive/assets/95973644/ea0a6f2e-5cb0-481c-abd8-7e3fbbbe3d93">

@ArslanYM

**Comment by ArslanYM** [comment]
Sure, youve been assigned to another feature. You can start working on that first.

**Comment by Pinaka-Pani-18** [comment]
Hi @ArslanYM Can I work on this issue ?

**Comment by ArslanYM** [comment]
Sure @Pinaka-Pani-18 , Assigned to you.

**Comment by ArslanYM** [comment]
Resolved in #315
