### ISSUE TITLE
[BUG]: /projects section isnt responsive

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#319]
### Description of the bug

TODO:
- Constant size of projectcard throughout the section 
- keep placeholders for logo that are not rendering 

### Please add screenshots (if applicable)

![1](https://github.com/ArslanYM/StarterHive/assets/104521101/0a937695-ea23-4b1a-82e4-20e320dbba4a)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [ ] I am willing to work on this issue (optional)

**Comment by khuzaima-a** [comment]
Assign this to me. I can do this surely

**Comment by ArslanYM** [comment]
@khuzaima-a Assigned to you. 🫱🏻‍🫲🏼

**Comment by khuzaima-a** [comment]
Done.
#327  fixes this issue
