### ISSUE TITLE
[BUG] : image/logo for project card is not placed correctly

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#320]
### Description of the bug

TODO:
- The logo of the projectCard in projects section shoud be placed correctly fiting the card 

### Please add screenshots (if applicable)

![2](https://github.com/ArslanYM/StarterHive/assets/104521101/627b42f0-6473-40ef-b0a8-30c78cdd123e)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [ ] I am willing to work on this issue (optional)

**Comment by ValkonX33** [comment]
hey i wanna work on this 
but can you guide me how should i start the local server?

**Comment by Sivasish48** [comment]
@ArslanYM Please rectify if I am incorrect, You want all the logos in the project section those be placed like the font awesome logo needs to be fixed like the way the Airform logo is placed in his card.

**Comment by ArslanYM** [comment]
> @ArslanYM Please rectify if I am incorrect, You want all the logos in the project section those be placed like the font awesome logo needs to be fixed like the way the Airform logo is placed in his card.

Yes thats right.

**Comment by ArslanYM** [comment]
@ValkonX33 You can refer to [this](https://github.com/ArslanYM/StarterHive/blob/main/web/README.md)

**Comment by vijaykrishna-11** [comment]
I am willing to work on this issue

**Comment by ArslanYM** [comment]
This issue has been resolved.
