### ISSUE TITLE
[BUG] : Remove light mode throughout the project.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#321]
### Description of the bug

TODO: 
- Remove everything associated with light mode throughout the project.
- remove light mode sections, coloring , etc
- remove toggle switch from navbar 
- Keep the project in dark theme only.

### Please add screenshots (if applicable)

![3](https://github.com/ArslanYM/StarterHive/assets/104521101/8858b246-20e0-4579-84b7-657598161f8f)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [ ] I am willing to work on this issue (optional)

**Comment by Henrique-mazzoleni** [comment]
hey @ArslanYM, can I work on this issue?

**Comment by ArslanYM** [comment]
@Henrique-mazzoleni Yes surely. Assigned to you.

**Comment by Henrique-mazzoleni** [comment]
@ArslanYM I think this issue is ready to be closed!
Thanks for letting me have a crack at it!

**Comment by ArslanYM** [comment]
Thankyou for your contribution @Henrique-mazzoleni
