### ISSUE TITLE
[BUG] : some logos are not rendering 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#322]
### Description of the bug

Some logos/images of project cards are not being displayed ,
check whats causing the issue and fix it 

### Please add screenshots (if applicable)

![4](https://github.com/ArslanYM/StarterHive/assets/104521101/ae65c301-a9b1-403e-93cc-fdefbe807101)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [ ] I am willing to work on this issue (optional)

**Comment by ArslanYM** [comment]
@shibuya-r Assigned to you. Feel free to ask any doubt's regarding the issue

**Comment by ArslanYM** [comment]
@haseeb196 This has been completed

**Comment by haseeb196** [comment]
> @haseeb196 This has been completed

i have checked the website the issue still exists. some logos are not rendering
