### ISSUE TITLE
⭐FEAT: Add chips in the project card for tags

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#323]
**Is your feature request related to a problem? Please describe.**
In the projects section , every project card should have tags as [chips](https://tailwind-elements.com/docs/standard/components/chips/) in the card.

**Describe the solution you'd like**
the [list of orgs](https://github.com/ArslanYM/StarterHive/blob/main/web/src/pages/Issues/ListOfOrgs/listOfOrgs.js)
contains a property called tags as well. Add those tags to the cards

*** 
Screenshots
![tags](https://github.com/ArslanYM/StarterHive/assets/104521101/f1ffcd1f-c638-403b-a8be-16b79658dea5)

**Comment by ValkonX33** [comment]
so you want the tags as chips elements right?

**Comment by ArslanYM** [comment]
> so you want the tags as chips elements right?
> 
> 

Yes that's right.
