### ISSUE TITLE
[BUG] The project cards needs to be centrally aligned on resize as well as cards need improvement

### ISSUE THREAD

**Issue by ratishjain12** [ArslanYM/StarterHive#332]
### Description of the bug

@ArslanYM Fix alignment of the projects as currently it is left aligned 

### Please add screenshots (if applicable)

![Screenshot 2023-09-15 205129](https://github.com/ArslanYM/StarterHive/assets/43003421/873fe89f-fa7c-45aa-9665-f63f424abe54)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [X] I am willing to work on this issue (optional)

**Comment by lucasfirmo62** [comment]
Hi @ratishjain12, I would like to make this issue.
Can you put me as Assignees? Can you tell me more about this bug?

**Comment by Sivasish48** [comment]
Please tell more detail about this bug
