### ISSUE TITLE
⭐FEAT:Add DropDown to choose language Show only selected Projects

### ISSUE THREAD

**Issue by Dhruvn-patel** [ArslanYM/StarterHive#340]
- Add DropDown like Below ss
![ss1](https://github.com/ArslanYM/StarterHive/assets/87563885/33feb03b-c696-4c3d-aa29-21093a424b61)

You have also create new features to Bookmarks projects so that users come next time directly goes to bookmark section and we can also add  favorite projects features

**Comment by amanrajrana** [comment]
Interesting issue. I am starting to work on this feature 👍

**Comment by amanrajrana** [comment]
Hi @ArslanYM , I would like to take on the interesting task of developing this feature. Could you assign it to me? 👍
