### ISSUE TITLE
⭐FEAT: Decrease the card size in the projects section.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#342]
## TODO: 
- Decrease project card size 
- the card should be responsive  for all devices 
- the card should have the same ui except for smaller in dimensions

***
The card looks like this rn: 
![decrease card size](https://github.com/ArslanYM/StarterHive/assets/104521101/164d8f46-4a5d-4a6f-802c-99b2f07e4746)

**Comment by Honey2339** [comment]
Would like on this. Can you assign me this issue?

**Comment by rajanarahul93** [comment]
I am interested in taking on the task at hand and want to assure you that I will complete it to the best of my ability. I kindly request that you assign this task to me #342 .

**Comment by ArslanYM** [comment]
Fixed in #342
