### ISSUE TITLE
⭐FEAT: Improve the docs section in the webapp

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#343]
## TODO: 
- Improve the ui of the docs section in the web app
- the docs section should provide the same info as [web/Readme.md](https://github.com/ArslanYM/StarterHive/tree/main/web#readme)
- the doc should be concise and better looking than current one

***
Currently it looks like this.
![the docs ](https://github.com/ArslanYM/StarterHive/assets/104521101/0b5f5c6d-a1a2-4acf-ad04-4a6e5492d5f6)

**Comment by kaushik17tripathi** [comment]
Is this good?

https://github.com/ArslanYM/StarterHive/assets/95939109/7f10141b-8b5d-4c59-9323-2967663bd51a

**Comment by ValkonX33** [comment]
@kaushik17tripathi  hey can you tell me how did you start the local development server of this repository, i mean what specific commands, i'm struggling with it from quite a while

**Comment by kaushik17tripathi** [comment]
@ValkonX33 In the project you have to change the directory to "web", then you can run "npm run dev" to start the server
<img width="953" alt="image" src="https://github.com/ArslanYM/StarterHive/assets/95939109/f842294a-d1fe-4b5f-90e8-4dc7282a729f">

**Comment by ArslanYM** [comment]
Yes please.
