### ISSUE TITLE
🔴[BUG] Enhance User Experience by Opening Projects in New Tabs

### ISSUE THREAD

**Issue by sree-hari-s** [ArslanYM/StarterHive#346]
### Description of the bug

For a smoother user experience in the Projects tab, it would be more convenient if clicking on a project opens it in a new tab instead of the same one.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [ ] I am willing to work on this issue (optional)

**Comment by inbuilt-aura** [comment]
Hey @sree-hari-s, I would like to contribute on this issue.Can i?
