### ISSUE TITLE
[FEAT]: Need a Guide to start development of web app on your local host.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#36]
The guide should : 
- Provide a crisp tutorial to start development on your local host.
- provide link to technologies used in the  web app
-  provide a easy guide for beginners as well 
Link to the Readme file : https://github.com/ArslanYM/StarterHive/blob/main/web/README.md

**Comment by shobhitexe** [comment]
Hey i will be very happy to take it can you plz assign this to me

**Comment by ArslanYM** [comment]
@shobhitexe Assigned to you. I hope you understand the feature im looking for. If you have any doubts feel free to ask.

**Comment by shobhitexe** [comment]
Yeah sure actually i have little doubt 
have added 
Tech Stack 
Prerequisites
and Additional resources to markdown

Should i add Steps of setting up locally and contributing 
or should i link it to https://github.com/ArslanYM/StarterHive#contributing

**Comment by ArslanYM** [comment]
No, actually we just started a react web app with vite, so the feature is to add a readme that can help people set up this web app locally and get started. After that you can add the step to contribute
