### ISSUE TITLE
[BUG] Overflow in Search Box on Mobile Screen

### ISSUE THREAD

**Issue by amanrajrana** [ArslanYM/StarterHive#361]
### Description of the bug

When accessing the [/contributors page](https://starter-hive.vercel.app/contributors) on a mobile screen with a resolution width of less than 400px, the search box is overflowing.

**Steps to Reproduce:**
1. Navigate to the [/contributors page](https://starter-hive.vercel.app/contributors).
2. Begin testing responsiveness.
3. Reduce the screen resolution width to less than 400px.

### Please add screenshots (if applicable)

**Device: Realme 5**

<img src="https://github.com/ArslanYM/StarterHive/assets/75106349/25e42768-0004-4774-bc9d-b3953f5168f4" height="450" alt="Screenshot">

**Galaxy Fold**
<img src="https://github.com/ArslanYM/StarterHive/assets/75106349/88761ec8-643e-4e53-baf9-857c143e0796" height="450" alt="Screenshot">

### Add any other context about the problem here

@ArslanYM add the label `hacktoberfest` in this issue

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [X] I am willing to work on this issue (optional)

**Comment by Tanush-J** [comment]
I am getting this behavior for Galaxy Fold in Chrome from devtools maybe this issue is specific to Brave browser

<img width="157" alt="image" src="https://github.com/ArslanYM/StarterHive/assets/75922615/6522a2ee-6004-414e-9270-8d9819bf60f0">

**Comment by amanrajrana** [comment]
> @amanrajrana Thankyou for the feature. Would love to have a discussion about some upcoming features on discord.

@ArslanYM How We can connect on Discord? Have you any discord server? If yes, then please provide me invitation link.

**Comment by ArslanYM** [comment]
[Discord Link](https://discord.com/invite/VkBTKUeVnG)
