### ISSUE TITLE
⭐FEAT: Dropdown Enhancement in Projects

### ISSUE THREAD

**Issue by sree-hari-s** [ArslanYM/StarterHive#370]
**Is your feature request related to a problem? Please describe.**
Its an issue to with the dropdown to find the right language/topic as it is jumbled

**Describe the solution you'd like**
Order it alphabetically

![image](https://github.com/ArslanYM/StarterHive/assets/48482060/8c5125b4-b4a3-4f5c-bc61-79694b67c495)

**Comment by ArslanYM** [comment]
Please raise a PR for this feature. @sree-hari-s

**Comment by sree-hari-s** [comment]
> Please raise a PR for this feature. @sree-hari-s 

I dont see any issue in the local environment. And it seems to work fine when tested locally.
