### ISSUE TITLE
[BUG] Hover effect on "Open Source" affecting visibility of "of"

### ISSUE THREAD

**Issue by roy7077** [ArslanYM/StarterHive#371]
### Description of the bug

I noticed an issue on the home page of the React website . When hovering over the text "Open Source," it appears that the size increases, and this is causing a problem with the visibility of the word "of." This issue affects the user experience and the overall readability of the content.

**Steps to Reproduce:**
1. Go to the home page of the website .
2. Hover the mouse cursor over the text "Open Source."

**Expected Behavior:**
The hover effect should not negatively impact the visibility of any part of the text.

**Actual Behavior:**
When hovering over "Open Source," the text appears to increase in size, and as a result, the word "of" becomes less visible.

### Please add screenshots (if applicable)

![Screenshot (133)](https://github.com/ArslanYM/StarterHive/assets/107414907/8f9687ce-33a8-47f4-86c9-8d0ce3f97ca3)

### Add any other context about the problem here

**Proposed Solution:**
To resolve this issue and improve the user experience, consider adjusting the CSS styles for the hover effect on the "Open Source" text. You may want to:

1. Ensure that the text size increase is not excessive or that it doesn't overlap with adjacent text.
2. Adjust the positioning or spacing of the text elements to prevent this issue.

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [X] I am willing to work on this issue (optional)

**Comment by ValkonX33** [comment]
Assign me this please

**Comment by ArslanYM** [comment]
> Assign me this please

@ValkonX33 Youve been assigned to tasks before and we havent received any PR regarding those. Do you want to get assigned to this?

**Comment by ValkonX33** [comment]
> > Assign me this please
> 
> @ValkonX33 Youve been assigned to tasks before and we havent received any PR regarding those. Do you want to get assigned to this?

i'm not assigned to any task as for now

**Comment by shubhampr07** [comment]
Assign this to me.

**Comment by Pushpajit** [comment]
Can you please assign this task to me
