### ISSUE TITLE
[FEAT] Add a folder structure to the project

### ISSUE THREAD

**Issue by nadeem099** [ArslanYM/StarterHive#38]
I suggest to go with the basic and beginner friendly "grouping by file type" folder structure.

- src
  - assets
  - components
    - Button.jsx
    - Card.jsx
    - index.js
   - contexts
   - helpers
   - layouts
   - pages

pages: pages will be combination of multiple components and will be mapped to a specific app route. This is helpful for beginners and new commers as it will be the entry point of application and through this folder they will be able to navigate to the rest of the codebase.

every folder will have `index.js` file in it which will export all the necessary functions/components required outside the folder.

optionally we can introduce `hoc`, `hooks` and `__tests__` if we need in future but we should avoid as it's not easy for beginners to understand.

To keep the codebase clean and maintainable:
 - We should avoid importing from other than index.js file of a specific folder.
 - Avoid creating nested folders, try to avoid more nesting at all.
 - Keep the files in the correct folder according to their types.

**Comment by nadeem099** [comment]
@ArslanYM, You can assign this to me, I can create the folder structure.

**Comment by ArslanYM** [comment]
Sure, Assigned to you

**Comment by ArslanYM** [comment]
@nadeem099 Will be a great help if you can add the structure a little faster. Have to start building the frontend

**Comment by ArslanYM** [comment]
@nadeem099  Sure, I actually had to create the project, So i started anyways

**Comment by nadeem099** [comment]
Thanks, I have added few changes, please review.

**Comment by ArslanYM** [comment]
DONE!
