### ISSUE TITLE
[FEAT]: Add link to the web app directory in the main Readme

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#39]
Add a link+ small description  in the main Readme file for people who want to contribute to the web app

**Comment by Shoetan** [comment]
Hi @ArslanYM. With a little more explanation, I think I can work on this issue. The link in the main Readme file will link to what?

**Comment by ArslanYM** [comment]
@Shoetan , So we have initialized a Web app in the /web directory. We need a small section in the main readme file that points to the web directory and gives a little detail of the web app for people who want to contribute for the web app.

**Comment by giri-madhan** [comment]
Hi @ArslanYM, I can work on this issue. Could you please assign the task to me? Thank you!

**Comment by ArslanYM** [comment]
@giri-madhan  I think @Shoetan wants to work on this. You can try out some other issues, Im sure theres  a lot

**Comment by giri-madhan** [comment]
Sure @ArslanYM . Thank you.

**Comment by Shoetan** [comment]
@ArslanYM thank you for the clarification. With your approval I'll love to work in this issue.

**Comment by ArslanYM** [comment]
@Shoetan Assigned to you.

**Comment by ArslanYM** [comment]
Fixed
