### ISSUE TITLE
[BUG] All Div Are Not In Same Size Or Good First Issues Box Are Of Random Size

### ISSUE THREAD

**Issue by Chetax** [ArslanYM/StarterHive#396]
### Description of the bug

All Div Are Not In Same Size We Have to Find Another Way to adjust all div

### Please add screenshots (if applicable)

![Screenshot 2023-11-14 212150](https://github.com/ArslanYM/StarterHive/assets/99749401/46bee083-d361-4ecf-a753-709a28a3a63f)

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [X] I am willing to work on this issue (optional)

**Comment by ArslanYM** [comment]
> ### Description of the bug
> All Div Are Not In Same Size We Have to Find Another Way to adjust all div
> 
> ### Please add screenshots (if applicable)
> ![Screenshot 2023-11-14 212150](https://user-images.githubusercontent.com/99749401/282838079-46bee083-d361-4ecf-a753-709a28a3a63f.png)
> 
> ### Add any other context about the problem here
> _No response_
> 
> ### Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
> * [x]  I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
> * [x]  I am willing to work on this issue (optional)

Do you want to work on this?

**Comment by Chetax** [comment]
@ArslanYM Yes I Want To Work On This Issue
