### ISSUE TITLE
[FEAT]: Add a detailed guide on how to how contributing to this project in the Readme.md file. 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#4]
//TODO: 

- Add a detailed guide on how to how contributing to this project in the Readme.md file. 
- Refer to CONTRIBUTING.MD file provided in the repo
- Use screenshots to guide beginners for making their first contribution

**Comment by Sohoxic** [comment]
Hey @ArslanYM , I'd love to work on this.

**Comment by ArslanYM** [comment]
> Hey @ArslanYM , I'd love to work on this. 

Sure, I'll assign you. Thankyou

**Comment by ArslanYM** [comment]
Completed!
