### ISSUE TITLE
Fix typo in CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by poorvijn** [ArslanYM/StarterHive#45]
There's a typo that says 'Starter Hived' instead of 'StarterHive'. 

Here it is:

![typo](https://github.com/ArslanYM/StarterHive/assets/87180220/bff5c6fc-145b-4e04-90c2-d4c90ea2e74f)

Would like to fix it!

**Comment by ArslanYM** [comment]
Thankyou. @poorvijn
