### ISSUE TITLE
[⭐FEAT]: Add github svg and link to github of this repo in the header file.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#50]
## TODO: 
- Add github svg icon in the button of header file
- it should redirect to the following [link](https://github.com/ArslanYM/StarterHive) when clicked on it.
![initial (2)](https://github.com/ArslanYM/StarterHive/assets/104521101/56211267-9e4f-4b80-bf3d-d8d7fe1ab65f)

**Comment by MuhammadRabi** [comment]
I can help with this issue too, if you allow me.

**Comment by ArslanYM** [comment]
@MuhammadRabi Assigned to you,
