### ISSUE TITLE
[⭐FEAT]: Make the project name in the header better looking.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#51]
//TODO: 
- Make the title in the header better looking and bold.
-  It should be the first thing that people notice when they land on the home page
![header](https://github.com/ArslanYM/StarterHive/assets/104521101/bfaa05f8-e756-45c8-aca7-02783c4a4fea)

**Comment by MuhammadRabi** [comment]
Hi, Arslan, I can help with this, Kindly assign it to me.

**Comment by ArslanYM** [comment]
Someone is already working on this. I have assigned another issue to you.

**Comment by MuhammadRabi** [comment]
That's fantastic! Thank you.

**Comment by ArslanYM** [comment]
Fixed
