### ISSUE TITLE
[⭐FEAT]: Need a logo for this project. 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#52]
//TODO: 
- To provide a logo that suits the features of this project and the name as well.
- to provide the logo for webapp as well as other uses.

**Comment by larbi1512** [comment]
@ArslanYM  I can help in that but I need further information !

**Comment by ArslanYM** [comment]
> @ArslanYM I can help in that but I need further information !

Sure, what info are you asking for?

**Comment by larbi1512** [comment]
do you need the logo to contain the name of the project or no ? and other stuff like that

**Comment by larbi1512** [comment]
and for the colors?
