### ISSUE TITLE
[⭐FEAT]: Provide a picture/image for the main page 

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#53]
Need a logo  or ui here
![here](https://github.com/ArslanYM/StarterHive/assets/104521101/176dff6c-cd49-4977-a229-ac5446ddf943)

**Comment by ArslanYM** [comment]
@Jussy562 Yes thats exactly what i wanna go for

**Comment by Jussy562** [comment]
If the custom picture is available, I can add it to the hero section.

**Comment by Jussy562** [comment]
If I should search for an illustration, let me know please

**Comment by ArslanYM** [comment]
Done!
