### ISSUE TITLE
⭐FEAT: Add new icons in the footer section.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#58]
TODO: 
- Add discord , twiiter and github icons in the footer instead of exisiting ones. 
-  The links for them are 
- Twitter: https://twitter.com/ArsalanYmalik
- Github: https://github.com/ArslanYM/StarterHive
- Discord: https://discord.gg/QBwU8KaJ

- 
![links](https://github.com/ArslanYM/StarterHive/assets/104521101/3f677514-a272-40ba-9502-3b6740fe0032)

**Comment by Kanchan253** [comment]
Hi @ArslanYM I would like to work on this. Kindly assign this to me.

**Comment by sharmakeshav10** [comment]
Hi @ArslanYM can you assign this to me? I would like to work on this issue.

**Comment by achhayapathak** [comment]
Is this still open?

**Comment by amratansh12** [comment]
Hey, I can work on this issue and can add some cool animation effects as well.
