### ISSUE TITLE
[FEAT]: Need a logo/ cover for this project.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#6]
// TODO: 
- Make a logo for this project 
- Make a cover for this project with its name on it. 
- The above mentioned should me minimal and match the name of the project.

**Comment by captainWaheed** [comment]
@ArslanYM  I am looking into this - For now, on cover for this project according to the requirements 🌠

**Comment by ArslanYM** [comment]
@captainWaheed Any progress bro?

**Comment by captainWaheed** [comment]
> @captainWaheed Any progress bro?

I will start working on the example cover, which I showed you earlier. Let me know the changes if required (also I was waiting for logo - if possible we can add in the cover)

**Comment by ArslanYM** [comment]
FIxed by @captainWaheed
