### ISSUE TITLE
⭐FEAT:Making the Header look more attractive

### ISSUE THREAD

**Issue by karthiknadar1204** [ArslanYM/StarterHive#61]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
 push the startedHive Text from top to the left and move the navbar links on the same side as the github links, I was thinking if making the navbar sticky and translucent with some box shadow so when the user scrolls down as we add more components, the navbar is consistent with his movements and the translucent background makes it look more attractive.
 
 Adding some additional hover effects also works out on the navbar links

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Please share your suggestions, something additional that you want me to add or dont want me to add

**Comment by karthiknadar1204** [comment]
I would like to work on this issue @ArslanYM

**Comment by karthiknadar1204** [comment]
@ArslanYM Please assign this issue to me

**Comment by ArslanYM** [comment]
@karthiknadar1204 try to keep the ui as minimal as possible and keep the commits clean. I feel like changing the alignment of header wont be a good addition. However you can try changing the color shading of the navbar

**Comment by ArslanYM** [comment]
Also on the home page there's going to be nothing else but the introduction so theres no point of making the navbar sticky or smn. However i would love to see what you wanna do

**Comment by karthiknadar1204** [comment]
Works

**Comment by rahilansari261** [comment]
Hey @ArslanYM 
if it not done yet can i do that ?
i'm thinking to make navbar look like as image below 
![Screenshot from 2023-05-26 17-19-13](https://github.com/ArslanYM/StarterHive/assets/12849916/b10d579a-d90d-44d0-bada-584827e49927)

**Comment by ArslanYM** [comment]
@rahilansari261 Do you want to work on the navbar?

**Comment by rahilansari261** [comment]
I would love to do it.
Do you have design in mind 🤔

**Comment by ArslanYM** [comment]
@rahilansari261 I really dont want to change much with the navbar, Just shift the header to the left , the navigation items ( home , contributor, etc) in the middle , and github at the right end. I would love it to be kind of towards the center. Right now its a little far from center. Lets make these changes first , then I will create a new issue for adding hover animations etc and you can work on those.. Thankyou for your time

**Comment by ArslanYM** [comment]
@rahilansari261 Have you made any progress on the navbar

**Comment by rahilansari261** [comment]
not yet 
i will do it toady

**Comment by ArslanYM** [comment]
> not yet i will do it toady

Some advice :
- Keep  the code clean
- use prettier to structure your code 
- only work on issues that are assigned to you
-

**Comment by ArslanYM** [comment]
@rahilansari261 Make sure to merge main into your branch before pr. New changes were added

**Comment by ArslanYM** [comment]
@rahilansari261 Any  updates?

**Comment by rahilansari261** [comment]
can you elobearte what is header means to you are you talking about the starter hive text and logo ?

> @rahilansari261 I really dont want to change much with the navbar, Just shift the header to the left , the navigation items ( home , contributor, etc) in the middle , and github at the right end. I would love it to be kind of towards the center. Right now its a little far from center. Lets make these changes first , then I will create a new issue for adding hover animations etc and you can work on those.. Thankyou for your time

**Comment by ArslanYM** [comment]
> can you elobearte what is header means to you are you talking about the starter hive text and logo ?
> 
> 
> 
> > @rahilansari261 I really dont want to change much with the navbar, Just shift the header to the left , the navigation items ( home , contributor, etc) in the middle , and github at the right end. I would love it to be kind of towards the center. Right now its a little far from center. Lets make these changes first , then I will create a new issue for adding hover animations etc and you can work on those.. Thankyou for your time
> 
> 
> 
> 

Yes

**Comment by rahilansari261** [comment]
> @rahilansari261 I really dont want to change much with the navbar, Just shift the header to the left , the navigation items ( home , contributor, etc) in the middle , and github at the right end. I would love it to be kind of towards the center. Right now its a little far from center. Lets make these changes first , then I will create a new issue for adding hover animations etc and you can work on those.. Thankyou for your time

merging this (https://github.com/ArslanYM/StarterHive/pull/149) PR will fix this issue
