### ISSUE TITLE
🔴 BUG: White, bar present beneath the footer, after device-height exceeds 993.328px with a ratio of 1, specifically visible on MacBook Air M2 (2022) with safari.

### ISSUE THREAD

**Issue by JaiS99** [ArslanYM/StarterHive#65]
**Describe the bug**
There is a big white bar, that is visible on safari browsers
The Black bar is the device frame and the red bar is where the white bar can be observed.
**To Reproduce**
1. Grab a M1/M2 Macbook Air 
2. Open the verbal deployment 
3. Scroll down form then footer to see the whitespace

**Expected behavior**
No white Space beneath the nabber should be present.

**Screenshots**
![Screenshot 2023-05-24 at 2 22 24 PM](https://github.com/ArslanYM/StarterHive/assets/48391316/347b842e-8795-4fba-a20b-c9c91ec1a07a)
**Additional context**
This does not appear to be a use agent problem as it is not present on the intel/mobile platform, I believe, it could only be limited to safari or it could be a major, css problem, further analysis is required.

**Comment by JaiS99** [comment]
Further analysis reveals that the viewport is 1470px x 867px but the html content spans 1470px x 795px, which leads to the white bar at the bottom, investigating further as to what could cause this.

**Comment by JaiS99** [comment]
<img width="1470" alt="Screenshot 2023-05-24 at 2 46 51 PM" src="https://github.com/ArslanYM/StarterHive/assets/48391316/54370ab0-d09c-4740-80c6-ad7766a6bae7">

**Comment by JaiS99** [comment]
I was also able to replicated this issue on windows, where, the website will not scale above height of 993.328px. Issue requires a deep dive into the project.

**Comment by JaiS99** [comment]
> @JaiS99 Thankyou for your interest in this project. A quick note:
> 
> * Dont start working on issues before getting assigned to them.
> * When raising an issue , keep the title short and crisp
> * Explain all the points related to that issue in one message.
>   Thankyou
> 
> Do you want to get assigned to this issue?

Thanks for the great piece of advice, I will surely, follow this for all my upcoming contributions.
I do not wish to get assigned to this issue.  I created this feeling that I had done wrong by not asking for assignment for the previous issue, 1 more for the folks to solve. I am glad I was able to help contributing.

**Comment by MuhammadRabi** [comment]
I can handle this bug @ArslanYM

**Comment by ArslanYM** [comment]
@MuhammadRabi assigned to you, Make sure to keep the commits clean and include this issues tag in your PR

**Comment by MuhammadRabi** [comment]
Sure I will, Thank you.

**Comment by JaiS99** [comment]
Bug fix complete!, website is looking great!

**Comment by ArslanYM** [comment]
Thanks
