### ISSUE TITLE
⭐FEAT: Make the size of icons in footer big

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#68]
TODO: 
- Make the size of social icons in footer bigger. 
- Add an hover effect as well 

![size](https://github.com/ArslanYM/StarterHive/assets/104521101/cb2d868d-c86a-4eaa-b468-1d442abbee1e)

**Comment by Vyom-V** [comment]
would you please assign this issue to me? :)

**Comment by ArslanYM** [comment]
@Vyom-V Sure thing, assigned to you.

**Comment by ArslanYM** [comment]
fixed in #76
