### ISSUE TITLE
⭐FEAT: Add a small arrow svg

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#73]
Add a small arrow button here : 

![arrow](https://github.com/ArslanYM/StarterHive/assets/104521101/04476775-20b7-4d1e-b565-d5d3a942bc43)

**Comment by Kruthardh11** [comment]
I would like to work on this

**Comment by ArslanYM** [comment]
@Kruthardh11 Assigned to you!!!

**Comment by ArslanYM** [comment]
Fixed!
