### ISSUE TITLE
⭐FEAT: Rearranging/Changing the styling of the text in the hero section.

### ISSUE THREAD

**Issue by Kruthardh11** [ArslanYM/StarterHive#75]
The text section in the home page can be made more attractive and prettier. The text together looks congested. Some padding and spacing will make this look good.

I would like to change the font and and little bit of shades to highlight keywords. Animation can also be added to the next and the button.  
![sh-1-edited](https://github.com/ArslanYM/StarterHive/assets/110627779/cd5cf352-a4ff-432a-b18a-727ec6d8ab26)

**Comment by Kruthardh11** [comment]
I would like to work on this if permitted

**Comment by Kruthardh11** [comment]
I have completed the other task. can you assign this one to me?

**Comment by ArslanYM** [comment]
@Kruthardh11 Sure thing !
