### ISSUE TITLE
[FEAT]: Provide a UI/UX mockup for the next version of this project.

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#8]
Provide a UI/UX mockup for the next version of this project.

The react app should have 
- a basic home page
- a good first issue finder search bar
- beginner friendly project cards

**Comment by karthiknadar1204** [comment]
@ArslanYM Can i take up this issue, i think i have some colour schemes/ideas that you might like

**Comment by ArslanYM** [comment]
@karthiknadar1204 Would love to assign it to you. You can share these mockups in the discord channel or just upload  them here. Goodluck

**Comment by karthiknadar1204** [comment]
https://www.figma.com/file/1wuz21qJCBs6TISJeS3Cke/Arsalan-Template_quine?type=design&node-id=0%3A1&t=3irREqXkW57hS2hm-1


Just a wireframe of the idea,can work more on the color scheme and a lot more @ArslanYM

**Comment by ArslanYM** [comment]
@karthiknadar1204 I think we can go with something better. Thankyou for your work tho.

**Comment by ArslanYM** [comment]
I have already initialized the frontend and the themes. I will close this issue. Thankyou
