### ISSUE TITLE
🔴 BUG: Hero button doesn't work

### ISSUE THREAD

**Issue by Soufianeelc** [ArslanYM/StarterHive#80]
**Describe the bug**
The button in the hero section doesn't take the user to the github issues.

**To Reproduce**
1. Go to the hero section
3. Click on "Find issues" button
4. Nothing will happen

**Expected behavior**
The user should be taken to the github issues when  clicking on the button

**Comment by ArslanYM** [comment]
@Soufianeelc This issue will be on hold because we havent built the issue section yet.
