### ISSUE TITLE
⭐FEAT: make the already existing readme.md guide better  looking in web folder

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#85]
# TODO: 
- Make the readme more readable and concise 
-  dont skip any of the poiints in the readme
-  your job is to make it better looking and concise 

Link : https://github.com/ArslanYM/StarterHive/tree/main/web#readme

**Comment by Kwamecody** [comment]
Hello, @ArslanYM ,

I would be very grateful if could you please assign me this task.

Thank you in advance.

**Comment by ArslanYM** [comment]
@Kwamecody Sure thing!!

**Comment by ArslanYM** [comment]
> Hello, @ArslanYM could you please elaborate more on what exactly or how you want the READ.md to look?

You can add guidance images or emojis wherever needed. Just make the readme a bit more readable. You can adjust the size of fonts etc.

**Comment by ArslanYM** [comment]
@Kwamecody  Has this been completed?

**Comment by Kwamecody** [comment]
@ArslanYM  No, please.

**Comment by Kwamecody** [comment]
@ArslanYM  Hello Sir, 
Please I have updated the README. Kindly have a look at it.
Sorry for taking soo much time.

**Comment by ayush-chandil** [comment]
Can I work on this issue if this is open ?

**Comment by ArslanYM** [comment]
Sure thing , Assigned to you.

**Comment by ayush-chandil** [comment]
https://github.com/ArslanYM/StarterHive/pull/307 I have raised a PR please do check it out.

**Comment by ArslanYM** [comment]
Fixed in #307
