### ISSUE TITLE
🔴 BUG: Cursor is not a pointer in NavBar

### ISSUE THREAD

**Issue by upadhyay8844** [ArslanYM/StarterHive#94]
**Describe the bug**
Hovering on to "Home", "Contributors", "Docs" and "Find Issues" cursor is not a pointer.

**To Reproduce**
hover on any thing on navbar

**Expected behavior**
As per better UX it should be pointer

Assign this to me will give it after doing the change.

**Comment by tylerpgen** [comment]
Anything that needs to be worked on I can be assigned to ?
