### ISSUE TITLE
⭐FEAT: Add divs to the hero section

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#97]
#TODO: 

- Add better looking divs to the main hero section instead of existing one div.
- For example : 
![Screenshot_2023-05-24_210450](https://github.com/ArslanYM/StarterHive/assets/104521101/e4492253-51bf-481b-959e-097dacedfca5)

The divs should be placed like this and later we must be able to insert an cover image inside.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue @ArslanYM

**Comment by ArslanYM** [comment]
Fixed in #99 , needs iteration
