### ISSUE TITLE
⭐FEAT: Add a section in the main Readme file

### ISSUE THREAD

**Issue by ArslanYM** [ArslanYM/StarterHive#98]
# TODO: 
- Add a section in the readme that navigates/points to Contributors.md file where first timers can  add thier names to the file and make a contribution
- Add a section in the readme asking frontend developers to contribute to web/ directory.

**Comment by martinyis** [comment]
Hey, could you assign this issue to me I would like to work on that

**Comment by ArslanYM** [comment]
> Hey, could you assign this issue to me I would like to work on that

Assigned to you!!!

**Comment by ArslanYM** [comment]
@martinyis Any progress?

**Comment by ArslanYM** [comment]
Fixed in #172
